ALTER TABLE "Shop"
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "checkInRadiusM" INTEGER NOT NULL DEFAULT 150,
ADD COLUMN "locationUpdatedAt" TIMESTAMP(3);
